apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j3c0ks0ux-java-springboot
  janus-idp.io/tekton: j3c0ks0ux-java-springboot
  backstage.io/kubernetes-id: j3c0ks0ux-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j3c0ks0ux-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
